languageCode = "en-us"
title = "Hello, it's Eliza speaking"
baseurl = "http://elizaspeaking.com/"
theme = "hugo-minimalist-theme"

# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "elizaspeaking"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-93022041-1"

[params]
    site_author = "Eliza Garton"
    site_description = "The awesome blog of Eliza Garton"
    location = "Wollongong, Australia"
    # Link custom assets relative to /static
    avatar = "img/avatar.jpg"
    header_background = "img/background_cropped.jpg"
    header_title = "Hello, it's Eliza speaking"
    copyright = "Eliza Garton"
    custom_css = ["css/custom.css"]
    custom_js  = []

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = "eliza.garton.5"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = "elizaspeaking"
    github    = ""
    gplus     = ""

