baseurl = "http://elizaspeaking.com/"
disqusShortname = "elizaspeaking"
googleAnalytics = "UA-93022041-1"
languageCode = "en-us"
paginate = 10
theme = "hugo-minimalist-theme"
title = "Hello, it's Eliza speaking"
[params]
avatar = "img/avatar.jpg"
copyright = "Eliza Garton"
custom_css = ["css/custom.css"]
custom_js = []
header_background = "img/background_cropped.jpg"
header_title = "Hello, it's Eliza speaking"
location = "Wollongong, Australia"
site_author = "Eliza Garton"
site_description = "The awesome blog of Eliza Garton"
[social]
behance = ""
dribbble = ""
facebook = "eliza.garton.5"
github = ""
gplus = ""
instagram = "elizaspeaking"
linkedin = ""
pinterest = "elizaspeaking"
twitter = "eliza_speaking"
